onnx: set CMAKE_CXX_STANDARD=17
error: 'string_view' in namespace 'std' does not name a
type this error pointed to using

this error pointed to using features that were supported in gcc17
and not gcc14 which is what was being used before.  Forcing onnx to use
gcc17 in order to allow compilation with those new features